# Use Rust docker image, see: https://hub.docker.com/_/rust/
image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
  script:
  - du -hs target
  - du -hs cargo
  - rustc --version && cargo --version
  - time cargo test --verbose --jobs 1 --release
  cache:
    paths:
      - target/
      - cargo/

